DROP TABLE IF EXISTS OrderHistories;
DROP TABLE IF EXISTS Orders;

CREATE TABLE Orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  status VARCHAR(32) NOT NULL,
  cost DECIMAL(10,2) NOT NULL,
  from_name VARCHAR(64) NOT NULL,
  address TEXT NOT NULL,
  product VARCHAR(128) NOT NULL,
  quantity INT NOT NULL,
  notes TEXT,
  shipping VARCHAR(32) NOT NULL,
  order_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OrderHistories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  shipping VARCHAR(32) NOT NULL,
  address TEXT NOT NULL,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (order_id) REFERENCES Orders(id) ON DELETE CASCADE
);
